### ISSUE TITLE
Add the ability to detect changes in libraries and publish them

### ISSUE THREAD

**Issue by jnsgruk** [canonical/charming-actions#10]
Nice work so far! :rocket: 

It would be great if this action could also detect changes in `lib/charms/<charm_name>/v#/<lib_name>` and publish updated version of charm libs. Thinking out loud, there are some gotchas:

- Need to ensure we only attempt to publish libraries for the charm in the repo, not those fetched for consumption
- Need to ensure that the `LIBPATCH` has actually been bumped and fail gracefully/warn if not

Tagging in @petevg and @simskij for the discussion too.

**Comment by simskij** [comment]
Sounds good to me!

**Comment by simskij** [comment]
After thinking a bit about this, I'd like to suggest we toggle this behavior using a boolean input to the action defaulting to true (enabled). There are definitely scenarios where we would like automatic lib publishing to be disabled, while still publishing the charm.

**Comment by simskij** [comment]
We've been discussing this more at multiple occasions, and while it sounds like an excellent idea at first, the fact that we only have one "channel" (ie. the latest revision) for libs, shared across all charm tracks and channels, it's not really desirable to have this automated. Will close this for now. If we come up with a good pattern for this we can revisit it later.
