### ISSUE TITLE
Create a new tag for actions with node16

### ISSUE THREAD

**Issue by natalian98** [canonical/charming-actions#101]
### Enhancement Proposal

The charming actions v2.3.0 use deprecated [node12](https://github.com/canonical/charming-actions/blob/a4a19eaf56a69deb271f1f76d7babf8107c3a1b5/upload-charm/action.yaml#L58). Github started enforcing migration to node16 (see [this](https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/) article). The main branch is already updated with the new version, but would it be possible to create a new tag for it?
With a new tag, renovate would open PRs to update repos which use the charming actions in CI.

**Comment by simskij** [comment]
Already fixed.
