### ISSUE TITLE
Tag the latest commit with the published charm revision when merging a PR.

### ISSUE THREAD

**Issue by DomFleischmann** [canonical/charming-actions#11]
Every time we merge a PR to `main` or a `track/foo` branch a charm will be published to `latest/edge` or `foo/edge` in charmhub.

It is easy to know what code corresponds to the charm in `edge` as it will always be the latest code. But once we start promoting different revisions we will lose track of that.

Therefore, when publishing a new charm we should also tag the latest commit in our git history with the charm revision of the published charm. That way we can search for these revisions easily in our git history.

This should only apply for when we publish to a channel, not for a charmhub branch

**Comment by simskij** [comment]
This has already been implemented.
