### ISSUE TITLE
Publish to a Charmhub branch for each PR

### ISSUE THREAD

**Issue by DomFleischmann** [canonical/charming-actions#12]
Every time we open a PR we should publish the built charm to a Charmhub branch.

For example, if we open a PR-25 for the git branch `track/1.4` the charm built in that PR should be pushed to the charmhub branch `1.4/edge/pr-25` everytime the CI of the PR is running. 

This will allow for easier testing of PRs as we will just have to pull the build from charmhub. Additionally, it will test if the charm is publishable before merging the PR.

**Comment by ca-scribner** [comment]
An option here to avoid unnecessary pushes to ch is that we only push to ch when a PR has a particular label (like `ok-to-push` or `push-to-dev-branch`, etc).  This would just need an extra if statement in our CI.

**Comment by jnsgruk** [comment]
I feel like that feature could be added, where you *can* specify a label to check, but if you don't specify the label it just pushed every time?

**Comment by DomFleischmann** [comment]
Yes, I believe that by default it should always push to Charmhub.

**Comment by simskij** [comment]
This is [already implemented](https://github.com/canonical/charming-actions/blob/2a52773e1eb7664cbbebc15b82511f6200707f60/src/services/ref/ref.ts#L44-L62). However, last time I checked it still wasn't fully supported in the charmcraft/-hub end.
