### ISSUE TITLE
[upload-charm] always uses the latest revision of the resource

### ISSUE THREAD

**Issue by nsklikas** [canonical/charming-actions#139]
### Bug Description

The `upload-charm` action:
1) pushes a resource to charmhub (https://github.com/canonical/charming-actions/blob/main/src/services/charmcraft/charmcraft.ts#L54)
2) Pulls all the resource's revisions and uses the latest (https://github.com/canonical/charming-actions/blob/main/src/services/charmcraft/charmcraft.ts#L56)

Perhaps this was caused by a (rogue?) charmhub API change, but if you push a resource to charmhub that already exists, that resource does not get a new revision. This wasn't always the case. 

This means that if a charm will always  use the latest resource version and not the one defined in the metadata.

Instead [uploadResource](https://github.com/canonical/charming-actions/blob/main/src/services/charmcraft/charmcraft.ts#L109) should run something like:
`charmcraft upload-resource <charm-name> oci-image --image <sha> --format json --verbosity brief`

And parse the output to get the revision, the call to list all the revisions is not needed.

### To Reproduce

Downgrade the image in a charm's metadata

### Environment

github?

### Relevant log output

https://github.com/canonical/kratos-operator/actions/runs/8919940662/job/24497519038 (the resource uploaded with the charm is a difference version from the one defined in the metadata)

**Comment by orfeas-k** [comment]
Great catch @nsklikas ! This has bitten us as well and we were really wondering why this happened. This happened when we updated the charm's resource to a previously used resource (in order to work around a juju bug temporarily) and while the publish succeeded, silently it kept using the previous image, since, as you highlight, this was the latest resource version ( the [CI run](https://github.com/canonical/kubeflow-dashboard-operator/actions/runs/9191524160/job/25323873832#step:5:470))

**Comment by DnPlas** [comment]
It looks like this is more a `charmcraft` behaviour rather than the action's. If you manually try to create a new revision of the resource that was already uploaded, charmcraft will just not allow it.

**Comment by nsklikas** [comment]
> It looks like this is more a charmcraft behaviour rather than the action's

Why? AFAICT charhmcraft provides you with all the info you need to do this properly.

The charmhub behavior changed some time in the past. It used to be that whenever you uploaded an image it would get a new revision, regardless if it was already uploaded. At the time the charmhub team refused to fix it, claiming it that this was the intended behavior. Now it looks like they have changed without any warning (?).

But this is the action's problem, I tried to explain it in the description. If you try to upload the same image multiple times, you will always get the same revision 
![image](https://github.com/canonical/charming-actions/assets/19745916/138841ea-884b-426f-86b0-c4bc067ba12a)

The action must parse parse the charmcraft output and use the revision number that is in the command's output, rather that always using the latest revision.

Am I missing something?
