### ISSUE TITLE
`upload-charm` action in 2.6.2 fails to create a release

### ISSUE THREAD

**Issue by jnsgruk** [canonical/charming-actions#148]
### Bug Description

When using the latest release (2.6.2), the `upload-charm` action fails to create an actual release.

Example failure: https://github.com/jnsgruk/zinc-k8s-operator/actions/runs/10247277256/job/28398779717

Can be fixed by reverting to 2.6.1: https://github.com/jnsgruk/zinc-k8s-operator/actions/runs/10266771820/job/28407051205

### To Reproduce

Try to release a charm with the 2.6.2 version of the action ;)

### Environment

n/a

### Relevant log output

```shell
See links above.
```

**Comment by orfeas-k** [comment]
hey @jnsgruk , in Kubeflow team, we have been using 2.6.2 all over our CI ([kfp-operators example](https://github.com/canonical/kfp-operators/blob/main/.github/workflows/publish.yaml#L86-L94)) and this has been working without issues. I also noticed the same observation in the linked PR above (https://github.com/canonical/charm-advanced-routing/pull/44#discussion_r1721067961). Is there something different that's specific to your use case? I didn't notice something in the [logs](https://github.com/jnsgruk/zinc-k8s-operator/actions/runs/10247277256/job/28398779717#step:4:104), neither in the way this is [being called](https://github.com/jnsgruk/zinc-k8s-operator/blob/main/.github/workflows/release.yaml#L41-L46) (apart from not using some optional arguments).

**Comment by jnsgruk** [comment]
Hmm, seems like it got bumped back to 2.6.2 and is in fact working again. I'll close this - thanks.
