### ISSUE TITLE
More sophisticated `check-libraries` output

### ISSUE THREAD

**Issue by sed-i** [canonical/charming-actions#41]
Ideally the action should adjust its output based on the differences between the repo and charmhub:

| Diff in lib repo vs ch | Lib version   | Output                |
|------------------------|---------------|-----------------------|
| No                     | repo = ch     | None (all ok)         |
| No                     | repo ≠ ch     | Inconsistency warning |
| Yes                    | repo = ch + 1 | None (all ok)         |
| Yes                    | repo ≠ ch + 1 | Inconsistency warning |

**Comment by simskij** [comment]
Agreed, this would be a good addition to the action.

**Comment by simskij** [comment]
After giving this some thought, my suggestion is as follows:

- No longer create a comment in the PR.
- Instead use labels to indicate the status:
  - `Libraries: In sync` if there are no issues
  - `Libraries: Out of sync` if there are any issues

**Comment by sed-i** [comment]
That's a neat simplification!
Would we need two labels? Maybe just one `outdated libs` is enough?

**Comment by taurus-forever** [comment]
@simskij I think the issue can be resolved with reference to https://github.com/canonical/charming-actions/pull/54

**Comment by sed-i** [comment]
There is one subtlety that the action does not yet capture:
When a PR updates libs that are owned by that same charm, AND version is bumped correctly, then `Libraries: Out of sync` is a bit misleading.

**Comment by simskij** [comment]
Well, it **is** in fact out of sync, even if the reason is less problematic 😜 I think this is good enough at this point. Closing the issue.
