### ISSUE TITLE
Add an action for publishing updated libs

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/charming-actions#43]
If a lib version / libpatch is updated, I'd like an action to publish it to charmhub.

If you could add me to the contributors and assign this to me, I'll open a PR soon :)

**Comment by simskij** [comment]
You already are :)

**Comment by paulomach** [comment]
Hey @PietroPasotti , just want to bump this up! We @data have great interest also

**Comment by lucabello** [comment]
This has been implemented through #47 and #78.
