### ISSUE TITLE
Improve `channel` action messaging when PR target is not as expected

### ISSUE THREAD

**Issue by ca-scribner** [canonical/charming-actions#51]
[this messaage](https://github.com/canonical/charming-actions/blob/c0a282a1dee7f014f983b076ecdd415f8d95926c/src/services/ref/ref.ts#L61) shows when, for example, the `channel` action is used on a PR that is against a feature branch (eg: PR from `some-branch` to `some-other-branch`, where the target is not the default branch or a `track/*` branch).  This message does not explain what is happening in a way someone without extra context could interpret.

**Comment by simskij** [comment]
Excellent observation! Feel free to provide a PR that makes the message more meaningful 👍🏼
