### ISSUE TITLE
The release-charm action currently fails for resourceless charms

### ISSUE THREAD

**Issue by simskij** [canonical/charming-actions#57]
As stated in the title, the `release-charm` action currently fails for resourceless charms. The reason seems to be that we're not guarding against empty resource blocks in the charmcraft output. This should solve itself when we move over to using the programmatic output, but we still need to track it here.

### Examples

- https://github.com/canonical/prometheus-scrape-config-k8s-operator/runs/7726893672?check_suite_focus=true
- https://github.com/canonical/prometheus-scrape-target-k8s-operator/runs/7726964781?check_suite_focus=true

### Likely problem

https://github.com/canonical/charming-actions/blob/39aea17818f4f2c6a6d0e23c55b9d37eb8bb7bb6/src/services/charmcraft/charmcraft.ts#L261-L275

(cc @agathanatasha)

**Comment by agathanatasha** [comment]
Could you update to 2.0.0-rc version where it parses the charmcraft status from json? I think it would work with resourceless charm

**Comment by simskij** [comment]
> Could you update to 2.0.0-rc version where it parses the charmcraft status from json? I think it would work with resourceless charm

That only changed it for the charm revision, but the fix is likely the same :)

**Comment by agathanatasha** [comment]
` getRevisionInfoFromChannel` is replaced by `getRevisionInfoFromChannelJson` in 2.0.0-rc
Updating works with one of kubeflow's resourceless charm
before update: https://github.com/canonical/kubeflow-roles-operator/runs/7139351420?check_suite_focus=true#step:3:23 (same error as yours)
after update: https://github.com/canonical/kubeflow-roles-operator/runs/7139483825?check_suite_focus=true#step:1:36

**Comment by simskij** [comment]
Closing this then. Thanks @agathanatasha !
