### ISSUE TITLE
Avoid race condition in getting resource revision

### ISSUE THREAD

**Issue by ca-scribner** [canonical/charming-actions#7]
[This](https://github.com/canonical/charmhub-upload-action/blob/63c5f1a9787998d31390696d482b0ac311f0709c/main.js#L112) uses `charmcraft resource-revisions` to get all revisions, then takes the top line as the resource we just uploaded.  This will often be true, but might not be if:
* charmcraft ever starts noticing we don't need to upload **everything**, **every time** and instead reuses old revisions
* (unlikely, but also really hard to debug) multiple publishes happen at once and the resource we pushed gets bumped down in the order

Suggested fix: parse revision number from the output from `charmcraft upload-resource` which says something like `Revision N created of resource ...`.

**Comment by knkski** [comment]
I think we should just wait until `charmcraft` supports a flag such as `--json-output` as suggested here:

https://github.com/canonical/charmcraft/issues/183#issuecomment-826882372
