### ISSUE TITLE
[check-libraries] Warning: 'Node.js 12' actions are deprecated. The following actions to use Node.js 16: check-libraries@2.2.2

### ISSUE THREAD

**Issue by taurus-forever** [canonical/charming-actions#83]
### Bug Description

It is a minor report, just to keep the house clean.
GitHub reports warning:
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: canonical/charming-actions/check-libraries@2.2.2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

You can find it here: https://github.com/canonical/s3-integrator/actions/runs/4004942011

### To Reproduce

Use "charming-actions/check-libraries@2.2.2" is GH CI/CD and check Actions->Summary->Warnings.

### Environment

GH Action with the latest availabe `check-libraries@2.2.2`

### Relevant log output

```shell
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: canonical/charming-actions/check-libraries@2.2.2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

### Additional context

The warning is obliviously reported for other actions too, e.g. `channel`:

```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, canonical/charming-actions/channel@2.1.0, canonical/charming-actions/upload-charm@2.1.0. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

in https://github.com/canonical/mysql-operator/actions/runs/3986561030

**Comment by dstathis** [comment]
Looks like `set-output` is also deprecated.

![workflows_deprecations](https://user-images.githubusercontent.com/2110777/217531415-d6fc4d43-7c12-439e-b72b-0e360db2df7f.png)

**Comment by taurus-forever** [comment]
> Looks like `set-output` is also deprecated.

Yes, `set-output` has [a separate](https://github.com/canonical/charming-actions/issues/66) bug-report.
